test_dataset:
  dataset:
    name: image-folder
    args:
      root_path: F:/benchmark/Set5/HR
  wrapper:
    name: sr-implicit-downsampled-swin2
    args:
      scale_min: 24
  batch_size: 1
eval_type: benchmark-24
eval_bsize: 30000

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}