test_dataset:
  dataset:
    name: image-folder
    args:
      root_path: F:/DIV2K/DIV2K_valid_HR
  wrapper:
    name: sr-implicit-downsampled-swin2
    args:
      scale_min: 18
  batch_size: 1
eval_type: div2k-18
eval_bsize: 

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}