test_dataset:
  dataset:
    name: image-folder
    args:
      root_path: F:/benchmark/manga109
  wrapper:
    name: sr-implicit-downsampled-swin2
    args:
      scale_min: 18
  batch_size: 1
eval_type: benchmark-18
eval_bsize: 30000

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}