test_dataset:
  dataset:
    name: paired-image-folders
    args:
      root_path_1: F:/DIV2K/DIV2K_valid_LR_bicubic/X4
      root_path_2: F:/DIV2K/DIV2K_valid_HR
  wrapper:
    name: sr-implicit-paired-swin2
    args: {}
  batch_size: 1
eval_type: div2k-4
eval_bsize: 

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}